<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    
    <!-- BOOTSTRAP 4.4 https://getbootstrap.com/docs/4.4/getting-started/introduction/ -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    
    <!--Font GOOGLE https://fonts.google.com/specimen/Krona+One?preview.text_type=custom-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Krona+One&display=swap" rel="stylesheet"> 

    <!-- css source C:\xampp\htdocs\mysite\jour6php\bd5926732641259-cocktails - départ\cocktails - de╠üpart\www\css\form.css -->
    <link rel="stylesheet" href="../www/css/form.css">

    <!-- Font Awesome 4.7 icon: https://fontawesome.com/v4.7.0/get-started/ link: https://cdnjs.com/libraries/font-awesome/4.7.0-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">

</head>
<body class="container-fluid">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
            <a class="navbar-brand" href="php/index.php"><img src="../www/images/logo/clovis-wood-photography-FT1PJqW0qtE-unsplash.jpg " alt="logo" style="max-width:80px"></a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="php/index.php">Home</a>
                </li>
            </ul>
            </div>
            </div>
        </nav>
    </header>
    <form action="updatecocktail.php"  method="POST">
        <fieldset>
        <legend> Modifier votre cocktail</legend>
            <!-- recuperer id du cocktail -->
            <input type="hidden" name="id" value="<?= htmlspecialchars($cocktails['cocktail_id']);?>"> 
            <label for="Nom">Nom</label>
            <input type="text" id="Nom" name="nom" value="<?= htmlspecialchars($cocktails["Nom"]);?>">
            <label for="Description">Description</label>
            <textarea type="textarea" id="Description" rows="4" cols="60" name="description"><?= htmlspecialchars($cocktails["Description"]);?></textarea>
            <label for="dateConception">Date conception</label>
            <input type="date" id="dateConception" name="dateConception" value="<?= htmlspecialchars($cocktails["dateConception"]);?>">
            <label for="prix">Prix proposé</label>
            <input type="number" id="prix" name="prix" value="<?= htmlspecialchars($cocktails['Prix_indicatif']);?>">
            <button type="submit">Soumettre</button>
        </fieldset>
    </form>
</body>
</html>